### ISSUE TITLE
Build on CI after webhooks from GitHub, Bitbucket, etc. and deploy to softcover.io.

### ISSUE THREAD

**Issue by cirosantilli** [softcover/softcover#100]
When the user pushes, a POST request is sent to a CI, which compiles and deploys artifacts to softcover.io.

The CI should also optionally return a POST request to the web interface so that further integration can be possible.

If this were done:
- people who use GitHub would be happier, as they would do a single `git push`, instead of `git push && softcover publish`
- more importantly: it would be possible to use Softcover without installing anything, just by using the browser.
  
  This would allow non technical users to use it, greatly increasing market share.
  
  Right now, I'm considering doing the same thing with some open source CI (Drone, Travis,). Your web interface is closed, is that it? Even so, if you support this idea I could just use some open source CI, and deploy with `softcover publish` from the CI. 
  
  Then, when that is possible, I will focus on hacking GitLab to make it better for book web editing.
  
  This is probably exactly what the closed source Inkling Habitat https://habitat.inkling.com is doing, currently with ugly browser dependent stuff. We could probably guess their stack from their open sourced stuff: https://github.com/inkling

**Comment by mhartl** [comment]
Cool, thanks.
