### ISSUE TITLE
nonstopmode for latex run silent not work

### ISSUE THREAD

**Issue by pussinboots** [softcover/softcover#110]
hy,

i try to automate building books with softcover and it goes very well but when it comes to latex errors than this console prompt cause me headaches if found a way to get ride of it by adding \nonstopmode to my latex file but it is also possible to pass the --interaction=nonstopmode option othe xelatex command. 

If you are interessting in than i can try to setup an pull request for that.

Great tool softcover motivates me to write my first book about Web Development.

**Comment by mhartl** [comment]
Added in 35ca0d411f07a84fa86213c2451e5c90b95287dd
