### ISSUE TITLE
Please don't insist on epubcheck in $HOME/bin

### ISSUE THREAD

**Issue by rrthomas** [softcover/softcover#114]
I've installed epubcheck 3.0.1 from Ubuntu, but `softcover check` insists that I have to download 3.0 and put it in `$HOME/bin`. Assuming sane version numbering, this seems excessively pendantic.

**Comment by mrandrewandrade** [comment]
@mhartl can you please put this in the instructions? I didn't know exactly where to put it until I stumbled upon this issue. Seems like I am not the only one (http://www.kaisataipale.net/blog/?p=65)

Maybe put something like:
     download and unzip
     mkdir $HOME/bin
     cp -r epubcheck-3.0 $HOME/bin

**Comment by mhartl** [comment]
As noted in the manual, EpubCheck can be placed anywhere in `$PATH`, and isn't restricted to `$HOME/bin`. Here's the code that finds it:

```ruby
    when :epubcheck
      # Finds EpubCheck anywhere on the path.
      cmd_path = ['epubcheck-3.0', 'epubcheck-3.0.jar']
      possible_paths = ENV['PATH'].split(File::PATH_SEPARATOR).
                                   collect { |x| File.join(x, cmd_path) }
      possible_paths.select { |f| File.file?(f) }.first || ""
```

I certainly welcome any corrections, but so far as I can tell the manual is correct as written and doesn't need to be updated.

**Comment by mrandrewandrade** [comment]
Thanks Michael.  I wasn't really sure where exactly to put it and creating the bin folder worked for me, so I was thinking anyone else who is confused could just do that.

**Comment by mrandrewandrade** [comment]
@mhartl  Would you like me to send you a PR with a quick edit on the manual for beginners like me not to get confused?  I didn't know how to add a folder on my `$Path`

**Comment by mhartl** [comment]
Sure, that'd be fine

**Comment by mrandrewandrade** [comment]
coolio, you can find it here: https://github.com/softcover/softcover_book/pull/5

Hopefully that will help beginners like me
