### ISSUE TITLE
Windows OS compatibility?

### ISSUE THREAD

**Issue by GarrettEttinger** [softcover/softcover#126]
Hello,

I'm working on editing a technical book about android programming, I am fairly new with the git repository but was wondering if you had any workarounds at all to get softcover on a windows OS? Right now I'm running the newest version of windows 8. 

Thanks in advance!

**Comment by mhartl** [comment]
Thanks for your question. Unfortunately, Softcover currently runs only on Unix systems (Linux & OS X), but we're working on a server-side version that lifts this restriction.
