### ISSUE TITLE
build:epub doesn't finish

### ISSUE THREAD

**Issue by ivanistheone** [softcover/softcover#127]
When I run a `build:epub` I see it starts, but it never seems to complete:
   $ softcover build:epub
   Building EPUB...

Note I'm compiling the basic a_chapter book that was generated by the `new` command.

I see `phantomjs` is running, but at 0 CPU.

After hitting CTRL+C  I see the following trace:

	^C/Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/output.rb:36:in ``': Interrupt
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/output.rb:36:in `system'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/builders/epub.rb:176:in `block (2 levels) in html_with_math'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.19/lib/active_support/core_ext/kernel/reporting.rb:45:in `silence_stream'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/builders/epub.rb:176:in `block in html_with_math'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/utils.rb:220:in `block in silence'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.19/lib/active_support/core_ext/kernel/reporting.rb:45:in `silence_stream'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/utils.rb:219:in `silence'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/builders/epub.rb:176:in `html_with_math'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/builders/epub.rb:144:in `block (2 levels) in write_html'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/builders/epub.rb:130:in `open'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/builders/epub.rb:130:in `block in write_html'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/builders/epub.rb:128:in `each'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/builders/epub.rb:128:in `each_with_index'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/builders/epub.rb:128:in `write_html'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/builders/epub.rb:54:in `build!'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/commands/build.rb:12:in `for_format'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/lib/softcover/cli.rb:54:in `block (2 levels) in <class:CLI>'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/gems/softcover-1.0.beta17/bin/softcover:4:in `<top (required)>'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/bin/softcover:19:in `load'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/bin/softcover:19:in `<main>'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
		from /Users/ivan/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'

	
For general info, I'm on Mac OS 10.6, with the following versions of things:

	$ softcover check
	Checking Softcover dependencies...
	Checking for LaTeX...         Found
	Checking for GhostScript...   Found
	Checking for ImageMagick...   Found
	Checking for Node.js...       Found
	Checking for PhantomJS...     Found
	Checking for Inkscape...      Found
	Checking for Calibre...       Found
	Checking for KindleGen...     Found
	Checking for Java...          Found
	Checking for zip...           Found
	Checking for EpubCheck...     Found
	All dependencies satisfied.

	$ phantomjs -v
	1.9.8

	$ tralics -v
	This is tralics 2.15.1, a LaTeX to XML translator, running on probook

Is there a way to turn on "dubugging info" in `builders/epub.rb` ?

**Comment by mhartl** [comment]
Thanks for the report. I'm unable to reproduce, but we'll keep our eye on
it. We're hoping to make a server-side version of the production system,
which would fix issues like this as a side-effect.

On Mon, Dec 29, 2014 at 9:42 AM, Ivan Savov <notifications@github.com>
wrote:

> I did some more tests and changes, notably moved project to a directory
> that does not contain spaces, and commented out the silence {
> silence_stream(STDERR) { system cmd } } and now I see this appears after
> some time:
>
> Timed out waiting for MathJax
>
> which seems to come from the code in builders/utils/page.js.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/softcover/softcover/issues/127#issuecomment-68279175>.
>



-- 
Michael Hartl
Author, Rails Tutorial <http://www.railstutorial.org/>
Founder, Softcover <http://www.softcover.io/>

**Comment by ivanistheone** [comment]
Followup: I believe I traced this problem to the Mac OS application security---the first time Inkscape runs it pops up a warning "This program was downloaded from the internet ... yada yada..." which was interfering with epub build. 

Works great now, so closing.

**Comment by mhartl** [comment]
:+1:
