### ISSUE TITLE
build:html fails without debug info

### ISSUE THREAD

**Issue by darmenise** [softcover/softcover#130]
When I try to build the html it fails with this trace:

```
Building HTML...
/Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/polytexnic-1.0.4/lib/polytexnic/postprocessors/html.rb:961:in `unescape_special_chars': undefined method `gsub' for nil:NilClass (NoMethodError)
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/polytexnic-1.0.4/lib/polytexnic/postprocessors/html.rb:946:in `block in hrefs'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/polytexnic-1.0.4/lib/polytexnic/postprocessors/html.rb:944:in `hrefs'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/polytexnic-1.0.4/lib/polytexnic/postprocessors/html.rb:45:in `xml_to_html'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/polytexnic-1.0.4/lib/polytexnic/postprocessor.rb:16:in `postprocess'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/polytexnic-1.0.4/lib/polytexnic.rb:85:in `to_html'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/softcover-1.0.5/lib/softcover/builders/html.rb:121:in `converted_html'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/softcover-1.0.5/lib/softcover/builders/html.rb:45:in `build'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/softcover-1.0.5/lib/softcover/builder.rb:18:in `build!'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/softcover-1.0.5/lib/softcover/commands/build.rb:12:in `for_format'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/softcover-1.0.5/lib/softcover/cli.rb:57:in `block (2 levels) in <class:CLI>'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/user/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/softcover-1.0.5/bin/softcover:4:in `<top (required)>'
    from /Users/user/.rbenv/versions/2.1.3/bin/softcover:23:in `load'
    from /Users/user/.rbenv/versions/2.1.3/bin/softcover:23:in `<main>'
```

Without pointing me in any direction.
`tralics.log` doesn't report any errors.
How can I proceed to fix the issue?

**Comment by railstutorial** [comment]
The only way I've found to debug such errors is to delete things until it builds, then add things back until it breaks. Once you've isolated the text that's causing the error, it's usually clear how to fix it.

**Comment by darmens** [comment]
Ok, I'll go this way.

**Comment by yiouyou** [comment]
@darmenise Any answers to this issue? I met the same problem. Thanks.

**Comment by mhartl** [comment]
@yiouyou It's the same answer I gave to @darmenise: Start with a working book. Add content until it breaks. The last change you made will tell you what's causing the problem.

**Comment by yiouyou** [comment]
@mhartl Yes, I did see your reply. I'm building a docker of softcover based on ubuntu 15.04. The error showed up when try to build the example_book.
-------------------------------------------------------------------------
root@aad5836742b8:~/exmaple_book# softcover build:all
Building all formats...
Building EPUB & MOBI...
/var/lib/gems/2.1.0/gems/softcover-1.1.11/lib/softcover/builders/html.rb:112:in `read': No such file or directory @ rb_sysopen - exmaple_book.tex (Errno::ENOENT)
        from /var/lib/gems/2.1.0/gems/softcover-1.1.11/lib/softcover/builders/html.rb:112:in `converted_html'
        from /var/lib/gems/2.1.0/gems/softcover-1.1.11/lib/softcover/builders/html.rb:43:in `build'
        from /var/lib/gems/2.1.0/gems/softcover-1.1.11/lib/softcover/builder.rb:18:in `build!'
        from /var/lib/gems/2.1.0/gems/softcover-1.1.11/lib/softcover/builders/epub.rb:133:in `build!'
        from /var/lib/gems/2.1.0/gems/softcover-1.1.11/lib/softcover/builders/mobi.rb:8:in `build!'
        from /var/lib/gems/2.1.0/gems/softcover-1.1.11/lib/softcover/commands/build.rb:30:in `block in all_formats'
        from /var/lib/gems/2.1.0/gems/softcover-1.1.11/lib/softcover/commands/build.rb:24:in `each'
        from /var/lib/gems/2.1.0/gems/softcover-1.1.11/lib/softcover/commands/build.rb:24:in `all_formats'
        from /var/lib/gems/2.1.0/gems/softcover-1.1.11/lib/softcover/cli.rb:28:in `build'
        from /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /var/lib/gems/2.1.0/gems/softcover-1.1.11/bin/softcover:4:in `<top (required)>'
        from /usr/local/bin/softcover:23:in `load'
        from /usr/local/bin/softcover:23:in `<main>'

**Comment by mhartl** [comment]
Is there a typo somewhere? You have `exmaple_book.tex` instead of `example_book.tex`.
