### ISSUE TITLE
PDF image problem

### ISSUE THREAD

**Issue by stefanotto** [softcover/softcover#131]
![screen](https://cloud.githubusercontent.com/assets/540502/7220235/90196ad6-e6c0-11e4-94ec-82bd66fffede.png)

Happens with a fresh book skeleton.

Running Yosemite 10.10.2, Command Line Tools 10.10 for Xcode 6.2.
All dependencies are satisfied with their latest releases.

**Comment by mhartl** [comment]
Is this a PDF made by printing the HTML? The PDF produced by `sc build:pdf` appears to work fine.

**Comment by stefanotto** [comment]
No, build with ```softcover``` as well.

**Comment by mhartl** [comment]
I'm unable to reproduce. Are you using a fresh book generated with `sc new`? This is what I get when running `sc build:pdf`:

![screen shot 2015-04-19 at 5 52 33 pm](https://cloud.githubusercontent.com/assets/6232/7222167/e506144e-e6bc-11e4-83a4-b6bac6772dd7.png)


![screen shot 2015-04-19 at 5 51 19 pm](https://cloud.githubusercontent.com/assets/6232/7222159/c5be353a-e6bc-11e4-96cc-b6531c2dce32.png)

**Comment by stefanotto** [comment]
Yes.

Maybe the terminal output helps: http://pastebin.com/DyWq0wyE

**Comment by mhartl** [comment]
Unfortunately, I'm still unable to reproduce the issue, which makes it tough to debug. Nothing in the log jumps out at me as the obvious source of the problem. The issue probably comes down to some subtle difference in the way `\includegraphics` behaves on our two systems. I suggest fiddling with the image code to see if you can successfully constrain the dimensions; once you do, let me know how you got it to work and I'll try to incorporate the changes into a future release.

**Comment by marcocevoli** [comment]
I have exactly the same issue here, on a fresh install on a Debian server.
