### ISSUE TITLE
Tables always rendered at top of page in PDF format

### ISSUE THREAD

**Issue by zengenuity** [softcover/softcover#132]
When I create a table in latex format, it's always shown at the top of whatever page it's supposed to be on, even if that means it moves above the other text on that page. (including text that is above the table in the source) It's only a problem in PDF format. The ordering is fine in all the other outputs.

Any idea what's going on? I'm just starting with softcover, so maybe I'm missing something here.

Source: https://gist.githubusercontent.com/zengenuity/ab14e216bd12669307ee/raw/408024b7569e263e3b7acf7a774431578902cfc6/blocks.md

Rendered output in PDF looks like this:

![screen shot 2015-07-23 at 3 15 43 pm](https://cloud.githubusercontent.com/assets/1405821/8859868/0a9a2fde-314e-11e5-97eb-571f911e3dd8.png)

**Comment by mhartl** [comment]
Table placement in PDFs is handled automatically by LaTeX and has nothing to do with Softcover *per se*. In particular, tables are a type of "float", so their placement in the text will often not correspond to the lexical order in the document. (This arises from the page-based nature of PDFs, which in turn derives from PDF's origins as a print format, and is an unavoidable restriction.) If you want to fiddle with table placement, I recommend consulting [LaTeX resources](http://lmgtfy.com/?q=latex+table+placement) directly.
