### ISSUE TITLE
How do I switch chapter and section for PDF?

### ISSUE THREAD

**Issue by mrandrewandrade** [softcover/softcover#135]
I am writing a book which can be broken into three section, each with their own chapters.  The order is fine, for example:
1 Section One
1.1 Chapter 1
1.1 Chapter 2

I tried switching them in the lang.yml (see below) but I only see the changes in the html version of the book, not the pdf.

The other issue is that it shows in the header of section (not chapter). How would I be able to change this?

    ---
    chapter:
        word: Section 
        order: standard     # Use 'reverse' to change 'Chapter 1' to '1 Chapter'
    section: Chapter 
    table: Table
    figure: Figure
     fig: Fig
    aside: Box
    listing: Listing
    equation: Equation
    eq: Eq
    frontmatter: Frontmatter
    contents: Table of Contents

I like the

**Comment by mrandrewandrade** [comment]
I tried grepping (grep -nr Chapter .) to find where it is in the latex file, but I couldn't find it.

./epub/OEBPS/a_chapter_fragment.html:6:          <title>Chapter 2</title>
./epub/OEBPS/another_chapter_fragment.html:6:          <title>Chapter 3</title>
./epub/OEBPS/frontmatter_fragment.html:6:          <title>Chapter 0</title>
./epub/OEBPS/yet_another_chapter_fragment.html:6:          <title>Chapter 4</title>
./epub/OEBPS/section_one_fragment.html:6:          <title>Chapter 1</title>
./config/lang.yml:4:  order: standard     # Use 'reverse' to change 'Chapter 1' to '1 Chapter'
./config/lang.yml:5:section: Chapter

**Comment by mhartl** [comment]
See [Foreign language support](http://manual.softcover.io/book/customization#sec-foreign_language) in the Softcover manual.

**Comment by mrandrewandrade** [comment]
Hi @mhartl , I don't think there is a solution for this. I followed the manual and changing the preamble and lang.yml does not fix this.  For the epub/mobi/html the changes work, but for the pdf it remains as "Chapter"

If I change the default language to French I get Chapitre 1

How do I change it to Section instead of Chapter or Chapitre ?

**Comment by mrandrewandrade** [comment]
So it seems like the "Chapter 1" is generated from the polyglossia package.  I threw up a question on [tex.stackoverflow.com](http://tex.stackexchange.com/questions/264268/xelatex-and-polyglossia-switching-chapter-and-section-titles)

**Comment by swhgoon** [comment]
@mrandrewandrade 
```tex
\renewcommand\chaptername{章}
\renewcommand\sectionname{节}
```
