### ISSUE TITLE
"softcover clean" doesn't clean everything

### ISSUE THREAD

**Issue by asmaier** [softcover/softcover#136]
After running 

    softcover build:html
    softcover clean

inside the `example_polytex_book` directory the following files seem to be left over:

    example_polytex_book.tex
    html/stylesheets/pygments.css
    latex_styles/polytexnic_commands.sty
    latex_styles/language_customization.sty

I think it would be more consistent, if `softcover clean` would delete those file, too.

**Comment by mhartl** [comment]
There's no need to remove any of these files, as they won't ever cause the build to fail. It's just the temp files and cache that need to be cleared.
