### ISSUE TITLE
How do I add a bibliography?

### ISSUE THREAD

**Issue by asmaier** [softcover/softcover#138]
I tried to use the latex commands `\begin{thebibliography}` `\end{thebibliography}`,  `\cite` and `\bibitem`. But it seems all these commands are ignored by softcover. 

So how do I add a bibliography to my book? How can I cite the entries? And are there any plans to support e.g. BibTex with softcover?

**Comment by mhartl** [comment]
BibTeX is not currently supported by Softcover. I suggest using footnotes instead. BibTeX support may eventually be added, but at present there's no timeline for its inclusion.

**Comment by asmaier** [comment]
Ok, I will use footnotes for now. But no support for citation and bibliography does make it much harder to convert an existing LaTex document to Softcover/PolyTex. And if Softcover wants to be an ebook typesetting system for technical authors I think it really should support a bibliography.

**Comment by mhartl** [comment]
*no support for citation and bibliography does make it much harder to convert an existing LaTex document to Softcover/PolyTex*

Right. I generally discourage this use-case.

*I think it really should support a bibliography*

This would have been much truer twenty, even ten years ago. The Web has changed the way people cite sources (generally for the better). I'd guess the vast majority of technical documents produced nowadays lack a formal bibliography. Like I said before, it's a possibility, but not a high priority.
