### ISSUE TITLE
Popups in HTML for footnotes and references

### ISSUE THREAD

**Issue by asmaier** [softcover/softcover#139]
The Feynman lectures have a cool feature: When one hovers over a footnote or a reference to an equation or image a popup is shown with the footnote or the equation, see e.g. http://www.feynmanlectures.caltech.edu/III_21.html.

Is there any chance we could see this feature in the HTML output of softcover, too?

**Comment by mhartl** [comment]
I just checked into doing it with [title text](http://www.paciellogroup.com/blog/2010/11/using-the-html-title-attribute/), but that doesn't work with any footnotes containing HTML structure (such as emphasis, links, etc.). The Feynman Lectures must be doing it with JavaScript, which is considerably more complicated, and thus not a top priority. Of course, Softcover is open-source, so you are welcome to add such a feature yourself. We would have to add some JavaScript to Softcover.io, which we'd be happy to do if it worked.

**Comment by asmaier** [comment]
I just found that the Feynman lectures seem to use javascript popups based on the code published at http://ignorethecode.net/blog/2010/04/20/footnotes/ .

**Comment by mhartl** [comment]
Thanks for the note. If we look into implementing this feature, that reference is likely to be very helpful.
