### ISSUE TITLE
Do you support book parts?

### ISSUE THREAD

**Issue by atsaloli** [softcover/softcover#140]
Hello,

My book is currently organized into parts, with about 7 chapters per part. 

Markdown doesn't seem to support book parts... Is it possible for me to implement book parts in SoftCover?

Best,
Aleksey

**Comment by mhartl** [comment]
There's no Part support yet. I should have emphasized that Learn Enough is an *articles* brand, i.e., a Learn Enough tutorial is in effect a single (possibly long) chapter. If the current approach to Vi is too big for this format, you should either limit the scope to fit it in a single article or make a book instead. In the latter case, we should probably discuss the details before proceeding, but fitting Vim inside an article could be a useful design constraint.

That said, you are welcome to try your hand at adding Part support to Softcover. Eventually I'll probably add it myself, but it's not a top priority.
