### ISSUE TITLE
Softcover won't read in CFEngine source files unless I change their names from *.cf to *.cf3

### ISSUE THREAD

**Issue by atsaloli** [softcover/softcover#141]
http://pygments.org/docs/lexers/ says *.cf are cfengine3 files

Yet when I try to read them in with <<(source/example.cf), Softcover says:

Building HTML...
/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:405:in `header_to_json': Traceback (most recent call last): (MentosError)
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 303, in start
    res = self.get_data(method, lexer, args, kwargs, text)
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 171, in get_data
    res = self.highlight_text(text, lexer, formatter_name, args, _convert_keys(opts))
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 122, in highlight_text
    lexer = self.return_lexer(lexer, args, kwargs, code)
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 79, in return_lexer
    return lexers.get_lexer_by_name(lexer, **inputs)
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/vendor/pygments-main/pygments/lexers/__init__.py", line 98, in get_lexer_by_name
    raise ClassNotFound('no lexer for alias %r found' % _alias)
ClassNotFound: no lexer for alias 'cf' found

Yet if I change my filename to example.cf3, it works (and I get the CFEngine highlighting).

Any suggestions?

**Comment by atsaloli** [comment]
Found in the Softcover manual that I can explicity specify the language, e.g.:

%= <<(path/to/filename.ext, lang: ruby)

And now I can read in my *.cf files

But is still seems that pygments should automatically recognize *.cf files as CFEngine source code... What is pygments.rb-0.6.3 and where does it come from?  Is it from pygments.org?  (this seems like a pygments.rb issue)   (I'm new to Ruby)

**Comment by mhartl** [comment]
It looks like the [pygments.rb gem](https://rubygems.org/gems/pygments.rb) doesn't yet support Pygments 1.5, which is required to lex `*.cf` files. Not much to be done here but wait, I'm afraid, unless you want to crack open `pygments.rb` and hack on it yourself…
