### ISSUE TITLE
How do I turn on line-numbering for included source code?

### ISSUE THREAD

**Issue by atsaloli** [softcover/softcover#142]
Hi,

Is it possible to turn on Pygments line numbering in included source files?

I couldn't find any mention of it in the Softcover book.

I tried:

```
%= <<(path/to/filename.ext, lang: ruby, linenos: true)
````

but that didn't work.

**Comment by mhartl** [comment]
See [here](http://manual.softcover.io/book/softcover_markdown#sec-code_fencing). Short version: `"linenos"` has to be part of an `options` hash, and it needs to be in quotes.
