### ISSUE TITLE
colored math text

### ISSUE THREAD

**Issue by sergeballif** [softcover/softcover#143]
The \coloredtexthtml command does not work in math mode for the html output. I have seen similar functionality in Mathjax (http://adereth.github.io/blog/2013/11/29/colorful-equations/). I would really like to use colored text to highlight parts of an equation.

**Comment by mhartl** [comment]
OK, just added. All that was needed was to add `color.js` to the MathJax config section. Run `gem install softcover -v 1.16` to install it.

**Comment by sergeballif** [comment]
I get an error. Do I need to do something special?
```
ballif@ballif-desktop ~ $ gem install softcover -v 1.16
ERROR:  Could not find a valid gem 'softcover' (= 1.16) in any repository
ERROR:  Possible alternatives: softcover
```

**Comment by mhartl** [comment]
Read the edited comment.

**Comment by mhartl** [comment]
> OK, just added. All that was needed was to add color.js to the MathJax config section. Run `gem install softcover -v 1.1.16` to install it.

**Comment by sergeballif** [comment]
I can confirm that the `\color` command from http://adereth.github.io/blog/2013/11/29/colorful-equations/ works in both the html and pdf output. However the `\coloredtexthtml` command isn't recognized by softcover when creating the html file. I can change all of my code to meet my needs, but I would suspect that others will try the `\coloredtext` and `\coloredtexthtml` in their math output in the future, so it is probably worth it to extend those commands so they work in math mode if possible. Thanks for being so quick with the changes.

**Comment by mhartl** [comment]
Softcover just passes the LaTeX intact through the production pipeline, so any unsupported features either aren't supported by MathJax or require further MathJax configuration. If the latter case, send me a pointer to the relevant config settings and I can add it to the gem.
