### ISSUE TITLE
Easier Mac installation with Homebrew

### ISSUE THREAD

**Issue by jackkinsella** [softcover/softcover#150]
As I was installing the gem today, I noticed the process could be scripted with some homebrew magic. The following might be a good addition to the readme or in-line help from the CLI interface.

``` zsh
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
brew install homebrew/binary/kindlegen
brew cask install mactex
brew install homebrew/gui/inkscape
brew cask install calibre
brew install epubcheck
brew install imagemagick
brew install ghostscript
brew install node
brew install phantomjs
```

**Comment by mhartl** [comment]
There used to be problems with several dependencies when installed via Homebrew. Can you confirm that the sample book generated by `softcover new` works with your setup as installed via `brew`?

```
$ softcover new test_book
$ cd test_book/
$ softcover build
```

**Comment by jackkinsella** [comment]
The build process went off without a hitch for me, successfully creating all three e-book formats. But I realised that I did not install Calibre with `brew`, having downloaded it directly from their website a year earlier. (I artificially added Calibre to the commands in my above message.)  

To better test, I uninstalled Calibre, re-installed via Homebrew, and ran `softcover build` again: it created the PDF and EPUB, but bugged out on the MOBI:
```
ImportError: dlopen(/opt/homebrew-cask/Caskroom/calibre/2.53.0/calibre.app/Contents/Resources/Python/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /opt/homebrew-cask/Caskroom/calibre/2.53.0/calibre.app/Contents/Resources/Python/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /opt/homebrew-cask/Caskroom/calibre/2.53.0/calibre.app/Contents/Resources/Python/lib/python2.7/lib-dynload/_io.so
```

**Comment by jarradh** [comment]
I also went the brew route, the only issue for me is that mactex was not added to my `PATH`
Adding `export PATH="/Library/TeX/texbin:$PATH"` resolved it and `softcover check` passes
