### ISSUE TITLE
Header numbering - is it possible to disable?

### ISSUE THREAD

**Issue by jackkinsella** [softcover/softcover#153]
The relaxed tone of the book I am writing doesn't gel well with the precision of numbered sections, so I was wondering if it is possible to disable these? 

If no such feature exists, I'd consider modifying the gem, but I'd need some guidance as to whereabouts this functionality comes from. (I couldn't locate it by scanning the code.)

**Comment by mhartl** [comment]
There's no way to disable the numbering, but you can try using `\chapter*{Name}` instead. This might mess up the table of contents, though.

I don't remember offhand exactly where the numbering comes in, though it's probably handled automatically by the Tralics LaTeX-to-HTML converter. Unfortunately, I don't have time right now to investigate further.
