### ISSUE TITLE
math equations not displaying properly in EPUB and MOBI

### ISSUE THREAD

**Issue by chkwon** [softcover/softcover#154]
In my Mac OS X, equations are not converted to graphics for displays in EPUB and MOBI. All dependency checks are passed. 

When I create a new book by `sc new sctest`, and `sc build:epub`, it still does not display equations properly: instead of graphics, I can only see the LaTeX source codes for the equations.

I guess this is an issue in my local system. Any guess? 

FYI:

```
chkwon@MacBook:sctest$ sc check
Checking Softcover dependencies...
Checking for LaTeX...         Found
Checking for GhostScript...   Found
Checking for ImageMagick...   Found
Checking for Node.js...       Found
Checking for PhantomJS...     Found
Checking for Inkscape...      Found
Checking for Calibre...       Found
Checking for KindleGen...     Found
Checking for Java...          Found
Checking for zip...           Found
Checking for EpubCheck...     Found
All dependencies satisfied.
```

```
chkwon@MacBook:sctest$ sc build:epub
Building EPUB...
  adding: mimetype (stored 0%)
  adding: META-INF/com.apple.ibooks.display-options.xml (deflated 26%)
  adding: META-INF/container.xml (deflated 33%)
  adding: OEBPS/a_chapter_fragment.xhtml (deflated 77%)
  adding: OEBPS/another_chapter_fragment.xhtml (deflated 62%)
  adding: OEBPS/content.opf (deflated 68%)
  adding: OEBPS/cover.xhtml (deflated 26%)
  adding: OEBPS/frontmatter_fragment.xhtml (deflated 74%)
  adding: OEBPS/images/cover.jpg (deflated 15%)
  adding: OEBPS/images/figures/01_michael_hartl_headshot.jpg (deflated 28%)
  adding: OEBPS/nav.xhtml (deflated 56%)
  adding: OEBPS/styles/custom.css (deflated 29%)
  adding: OEBPS/styles/custom_epub.css (deflated 40%)
  adding: OEBPS/styles/epub.css (deflated 43%)
  adding: OEBPS/styles/page-template.xpgt (deflated 80%)
  adding: OEBPS/styles/pygments.css (deflated 79%)
  adding: OEBPS/styles/softcover.css (deflated 75%)
  adding: OEBPS/toc.ncx (deflated 64%)
  adding: OEBPS/yet_another_chapter_fragment.xhtml (deflated 60%)
```

**Comment by mhartl** [comment]
Problems with raw LaTeX instead of images probably indicates an issue with
the PhantomJS dependency. Try double-checking the installation to see if
that helps.

On Sun, Mar 27, 2016 at 1:46 PM, Changhyun Kwon <notifications@github.com>
wrote:

> In my Mac OS X, equations are not converted to graphics for displays in
> EPUB and MOBI. All dependency checks are passed.
>
> When I create a new book by sc new sctest, and sc build:epub, it still
> does not display equations properly: instead of graphics, I can only see
> the LaTeX source codes for the equations.
>
> I guess this is an issue in my local system. Any guess?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/softcover/softcover/issues/154>
>



-- 
Michael Hartl
michaelhartl.com

**Comment by chkwon** [comment]
I've installed PhantomJS again:

```
chkwon@MacBook:sctest$ which phantomjs
/usr/local/bin/phantomjs
chkwon@MacBook:sctest$ phantomjs
phantomjs> 

```

No good. Any test code to see if PhantomJS works good?

**Comment by chkwon** [comment]
In `lib/softcover/builders/epub.rb`, I found the following codes:

```ruby
# Sometimes in tests the phantomjs_source.html file is missing.
# It shouldn't ever happen, but it does no harm to skip it.
return nil unless File.exist?('phantomjs_source.html')
raw_source = File.read('phantomjs_source.html')
```

It seems like the file `phantomjs_source.html` does not exist in my system, and therefore just skip the rest of the epub building. How can I create or generate `phantomjs_source.html`?

**Comment by mhartl** [comment]
That line only applies in tests. When the system is running normally, the PhantomJS file is created and then removed automatically.

**Comment by chkwon** [comment]
Oh well, my version of `phantomjs` was `2.1.1`, which actually produced the MathJax timeout error. 

After changing it to version `1.9.8`, it works. I'm in Mac OS X.

**Comment by mhartl** [comment]
Great, thanks for the details and glad to hear you got it to work. I'll
look into updating the docs with a specific version number, and might also
investigate version 2 compatibility.

On Sun, Mar 27, 2016 at 4:45 PM, Changhyun Kwon <notifications@github.com>
wrote:

> Oh well, my version of phantomjs was 2.1.1, which actually produced the
> MathJax timeout error.
>
> After changing it to version 1.9.8, it works. I'm in Mac OS X.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/softcover/softcover/issues/154#issuecomment-202169518>
>



-- 
Michael Hartl
michaelhartl.com

**Comment by chkwon** [comment]
Update: After upgrading to Sierra, `phantomjs 1.9.8` is no longer compatible. EPUB generation with math equations in Mac OS X is not possible.

**Comment by mhartl** [comment]
Thanks for the heads up. This is awful news, as it's the kind of thing that could easily be impossible to fix, and of course it's a giant waste of time to have to fix something that was working fine for the past several years. I'll do my best to get it working.

**Comment by mhartl** [comment]
It looks like PhantomJS 2.1.1 runs on macOS Sierra, but it doesn't appear to work with MathJax. I have no idea how to fix it offhand, but it's critical that I figure it out at some point. As I said before, it may just not be possible. Not sure what we'll do if that's the case.

**Comment by chkwon** [comment]
Thanks. Hope for a good news. I've tested in Ubuntu and also found out that PhnatomJS 2.1.1 does not work well with softcover. I had to use 1.9.8.

**Comment by mhartl** [comment]
OK, this was a nasty one. Not only did PhantomJS 1.9 break on Sierra, but (as you noted) changes to version 2.1.1 broke compatibility with the `softcover` gem. PhantomJS 2 is also incompatible with the older version of MathJax that came bundled with Softcover. Finally, the latest version of MathJax is compatible with PhantomJS but is (slightly) incompatible with the SVG-extraction algorithm used by Softcover's `page.js` script.

I believe I've tracked down all the issues and now have a working version. Try out the new 1.3.0 gem to see if it works for you:

```bash
$ gem update softcover -v 1.3.0
```

**Comment by chkwon** [comment]
Thanks! I just confirmed the new softcover version works good in Ubuntu with PhantomJS 2.1.1. I'm testing now in macOS Sierra.

**Comment by chkwon** [comment]
In macOS Sierra, it doe not work. `sc build:epub` runs well, but it actually produces all blank math images. As I check `epub/OEBPS/images/texmath` folder, there are PNG files with different pixel sizes but all blank.

**Comment by axitdn** [comment]
I have the same issue. OSX Yosemite, PhantomJS 2.1.1. Softcover 1.3.0

**Comment by mhartl** [comment]
It's working on both systems I have access to (Yosemite & Sierra). Unfortunately, there's not much I can do if I can't reproduce the issue, so any help would be appreciated.

![screen shot 2016-10-17 at 11 54 47](https://cloud.githubusercontent.com/assets/6232/19451021/8a9fdd20-9460-11e6-8cf6-1aa07e73976e.png)

**Comment by chkwon** [comment]
On a fresh Sierra, I did the following:
```
xcode-select —install
Installing homebrew
brew install ruby
brew install node
brew cask install quartz
brew cask install Inkscape
brew cask install calibre
brew cask install kindlegen
brew install epubcheck
brew cask install java
brew install phantomjs
brew cask install basictex (then later open /usr/local/Caskroom/basictex/20161009/mactex-basictex-20161009.pkg)
brew install ghostscript
brew install imagemagick
sudo gem install —no-ri —no-rdoc softcover
```

It doesn't work. Do you think manual installation of dependencies will make any difference? @mhartl

**Comment by mhartl** [comment]
Manual installation of (most) dependencies is a good idea, as described [here](http://manual.softcover.io/book/getting_started#sec-installing_softcover). Not sure what to do if you can't get it to work; as noted before, it's working on all the systems I have access to.

**Comment by chkwon** [comment]
It might be inkscape. After un-muting [this line](https://github.com/softcover/softcover/blob/master/lib/softcover/builders/epub.rb#L362), I obtained the following warning:
```
** (inkscape-bin:8074): WARNING **: SPIStyle::readIfUnset(): Invalid style property id: 90 value: static
Background RRGGBBAA: ffffff00
Area -1:-1:0:0 exported to 83 x 83 pixels (7470 dpi)
Bitmap saved as: /Users/chkwon/Documents/Repositories/sctest/epub/OEBPS/images/texmath/e2293e769a19cf7cc131560e7d30a493cf399b8a.png
```

I checked with the SVG file, and it contained a correct math equation, while the converted PNG file is blank. [Here](https://gist.github.com/chkwon/6ac383f4275720402027b3b7d4614ac1) is the generated SVG file. 

The SVG file looks incompatible with Inkscape, at least my version (Inkscape 0.91 r13725 (Jan 28 2015). I tested inkscape file conversion with another SVG file downloaded from the web, and it went well.

**Comment by chkwon** [comment]
I've tested the SVG file generated in macOS in my Ubuntu. It is converted well. So there is no problem with the SVG file itself.

It seems that the current Mac version of Inkscape has some issues for conversion. I tested a previous version of Inkscape (v0.48.5) and it works well.

**Comment by chkwon** [comment]
@mhartl @axitdn Could you let me know your Inkscape version installed on your mac?

**Comment by chkwon** [comment]
I reported this to Inkscape and someone is working on it.

https://bugs.launchpad.net/inkscape/+bug/1634571

**Comment by mhartl** [comment]
OK, sounds like it's an Inkscape issue. I'll plan to keep an eye on it.

**Comment by axitdn** [comment]
@chkwon My Inkscape version is 0.91. I will try the Inkscape (v0.48.5). For now, my workaround is building a Softcover Docker version. 
// @mhartl Do you have an official docker version for Softcover?

**Comment by mhartl** [comment]
There's no official Docker build.

**Comment by robconery** [comment]
I was able to get around this on sierra by using the 0.48.5 build of inkscape, which you can download from here:
https://inkscape.org/en/release/0.48.5/platforms/

Hope this helps someone... this was a big pain :).

**Comment by ivanistheone** [comment]
@robconery thanx for the pointer. 

(On Mac OS X 10.10.5, using Inkskape 0.91 produces blank `.png`s for the math. Using the older 0.48.5 build makes math image generation work again. That's odd because I used 0.91 before and it worked fine).
