### ISSUE TITLE
size of equations in MOBI

### ISSUE THREAD

**Issue by chkwon** [softcover/softcover#155]
Mathematical equations are too small in MOBI (in other formats, they are all fine.) Please see the screenshot:

<img width="521" alt="screenshot 2016-04-09 16 15 11" src="https://cloud.githubusercontent.com/assets/7596204/14406186/5cdcf1bc-fe6e-11e5-9836-b7c3f4323592.png">

With a larger font size:

<img width="521" alt="screenshot 2016-04-09 16 15 16" src="https://cloud.githubusercontent.com/assets/7596204/14406191/67043196-fe6e-11e5-9615-69a6797a9c48.png">

I used Kindle Previewer 3 version 3.3.5.28.0 on Mac OS X.

**Comment by mhartl** [comment]
Could you let me know the result of running `softcover -v`?

**Comment by chkwon** [comment]
It is `Softcover 1.2.6`

**Comment by mhartl** [comment]
OK, try upgrading to the latest version (1.2.7) using `gem update softcover`. It's possible it still won't be much better, though; getting math to work in EPUB and MOBI documents at all is exceptionally difficult.

**Comment by chkwon** [comment]
Beautiful! Everything looks good with version (1.2.7). Thanks!!!
