### ISSUE TITLE
Possibly unnecessary dependencies in .gemspec

### ISSUE THREAD

**Issue by adamniedzielski** [softcover/softcover#157]
Hey! I wonder why this gem depends on `msgpack`, `kramdown` and `maruku`. There is no trace of usage of these gems in the codebase. `msgpack` and `kramdown` are dependencies of the `polytexnic` gem. `maruku` looks like the predecessor of `kramdown`.

Am I missing some additional context here? Will you accept a pull request removing these dependencies from this gem?

**Comment by mhartl** [comment]
It's entirely possible that there are some old disused dependencies. I'd be happy to accept a pull request removing them. Just be sure the test suite still passes. Thanks!
