### ISSUE TITLE
URL names that contain /_/ get incorrectly parsed

### ISSUE THREAD

**Issue by nickjj** [softcover/softcover#158]
**I want** to write out a URL like this:

```
[https://hub.docker.com/_/python](https://hub.docker.com/_/python)
```

**but**, the output is:

```
[https://hub.docker.com//python](https://hub.docker.com//python)

# ^ It automatically strips the _ in the anchor name.
```

**however**, as a compromise this works for now:

```
[https://hub.docker.com/-/python](https://hub.docker.com/_/python)
```

**but**, it's a little silly having to do this because the written anchor name is no longer matching the URL.

**Comment by chkwon** [comment]
Can you try 

\url{https://hub.docker.com/_/python}

?



> On Apr 16, 2016, at 3:48 PM, Nick Janetakis <notifications@github.com> wrote:
> 
> I want to write out a URL like this:
> 
> [https://hub.docker.com/_/python](https://hub.docker.com/_/python)
> but, the output is:
> 
> [https://hub.docker.com//python](https://hub.docker.com//python)
> 
> # ^ It automatically strips the _ in the anchor name.
> however, as a compromise this works for now:
> 
> [https://hub.docker.com/-/python](https://hub.docker.com/_/python)
> but, it's a little silly having to do this because the written anchor name is no longer matching the URL.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/softcover/softcover/issues/158>

--

**Comment by mhartl** [comment]
You might need to escape it out, like this:

```
[https://hub.docker.com/\_/python](https://hub.docker.com/_/python)
```

Does that work?

**Comment by nickjj** [comment]
@chkwon,
That produces this: https://hub.docker.com//python, but the URL itself works.

@mhartl,
That works, thanks. Kind of unfortunate that we need to escape it, but it works in the end.
