### ISSUE TITLE
Constant tilt warnings stop automatic reload of sc server

### ISSUE THREAD

**Issue by ajhenley** [softcover/softcover#160]
I keep getting some variation of this message
WARN: tilt autoloading 'tilt/erb' in a non thread-safe way; explicit require 'tilt/erb' suggested.

and when it happens I don't get any more refreshes until I restart sc server.

It only seems to happen when I save bad markdown/latex, but since I am just learning that will happen alot I figure. Is this a known problem? Everything else seems to work fine...

**Comment by mhartl** [comment]
I get similar errors from time to time, but it's safe to ignore them. Thread-safe loading matters only if you're using the software in a multithreaded environment, which you definitely shouldn't do. You're welcome to dig into the source code and submit a pull request with a fix, but I doubt it's worth the trouble.

**Comment by ajhenley** [comment]
But when you have them happen is your autorefreshing failing?

**Comment by mhartl** [comment]
Ah, no. The autorefresh keeps working. In fact, I think I only ever get the warnings when I fire up the server for the first time.

**Comment by ajhenley** [comment]
Yeah, I am seeing it regularly like I said and when it happens the refresh
stops working so I am basically Ctrl + c ' ing and restarting the server
regularly....

On Fri, Jun 3, 2016 at 11:22 AM, Michael Hartl <notifications@github.com>
wrote:

> Ah, no. The autorefresh keeps working. In fact, I think I only ever get
> the warnings when I fire up the server for the first time.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/softcover/softcover/issues/160#issuecomment-223609255>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAM6QBpqvs4DsNyzVxfT_LwcDM884RH3ks5qIEbFgaJpZM4ItGDR>
> .
>



-- 
Not sent from my iPhone

**Comment by mhartl** [comment]
You definitely shouldn't have to do that. I'll take a look at it.

**Comment by mhartl** [comment]
OK, try installing the new release:

```
gem install softcover -v 1.2.11
```

Let me know if that fixes the issue.
