### ISSUE TITLE
sc server fails without remote staging

### ISSUE THREAD

**Issue by alexvbush** [softcover/softcover#162]
Running `sc server` or any other command gives me `Error: Could not find git remote staging in /Users/Alex/workspace/softcover_book`. Do I have to create a staging remote for the project?

**Comment by mhartl** [comment]
No, you definitely don't need a staging remote to use Softcover. In fact, Softcover never uses Git directly, so the error message doesn't make any sense in this context. 

Is it possible that the `sc` command is aliased to something else on your system? I suggest trying the full `softcover` command to see if that works.

**Comment by alexvbush** [comment]
omg, indeed that was the case! so sorry for such a sloppy mistake. thank you @mhartl !
