### ISSUE TITLE
Docs suggestions

### ISSUE THREAD

**Issue by donnekgit** [softcover/softcover#164]
In 3.1.3 you talk about escaping characters.  It would maybe be worth adding the pipe character (|) to the list, since it's quite widely used to chain commands in Linux, but if it's referred to unescaped in the text it will be interpreted as a table border command, and the text will get table borders around it.

In 2.1 you say:

> It is important to note that each Softcover chapter file corresponds to exactly one chapter. This means that you can only include one top-level # heading in any given file.

I think this needs to be given **much** more emphasis, addressing especially those who are importing existing Markdown files which may not have had this constraint applied (ie there is more than one # header in the file).  Attempting to build will then give the error:
```
in `block in split_into_chapters': undefined method `slug' for nil:NilClass (NoMethodError)
```
(possibly another one for a potential Troubleshooting chapter?) until the chapter is split, or all other # headers except the first are downgraded to ##.  (It does build the book-on-one-long-page html, but not the chapter-on-one-page html, but doesn't actually tell you that.)

**Comment by mhartl** [comment]
Thanks for the notes. I've added `|` to the list of escaped characters. 

I've also released a new version of the gem that catches the `NoMethodError` and gives a more helpful error message. Run `gem update softcover` to get the latest version.

Thanks!
