### ISSUE TITLE
Article Draft? option in Book Controls

### ISSUE THREAD

**Issue by alexvbush** [softcover/softcover#165]
Hi, what `Article Draft?` option does when you turn it on? Couldn't find it anywhere in the docs or in this repo.

**Comment by mhartl** [comment]
It just adds a note to the article indicating it's a draft. Try it and see!

**Comment by alexvbush** [comment]
Does the reader see it? don't see it anywhere

**Comment by mhartl** [comment]
It should display as shown. You might have to enable public viewing as well. 

![screen_shot_2016-08-06_at_8_06_39](https://cloud.githubusercontent.com/assets/6232/17457425/e3c4439c-5bac-11e6-9758-d7a6c3394d28.png)
