### ISSUE TITLE
Any future plans to add comments feature?

### ISSUE THREAD

**Issue by alexvbush** [softcover/softcover#166]
Hi @mhartl great tool, love it! Was wondering if you ever thought of adding commenting feature to book? Feel like it would be great for readers to comment right on a specific paragraph for example, ideally medium style :) 
The way I see it it could increase users engagement with your content if they can chat right here and there.

**Comment by mhartl** [comment]
Experience shows that such comments can be a maintenance nightmare. We may consider adding it at some point, but it's not a top priority.
