### ISSUE TITLE
Single page functionality

### ISSUE THREAD

**Issue by jasonnoble** [softcover/softcover#169]
I see on http://manual.softcover.io/book the ability to click "Single Page" and get the entire book as one long HTML page (http://manual.softcover.io/book/_single-page).

Is that functionality available when I'm running `softcover server`?

**Comment by mhartl** [comment]
Yes, just open the file in the `html` directory corresponding to the full book. It's just a regular HTML file, so it won't reload automatically the way localhost:4000 does, but all the content will be there.
