### ISSUE TITLE
How would you adjust header/body fonts globally?

### ISSUE THREAD

**Issue by nickjj** [softcover/softcover#170]
Hello,

I couldn't find this in the documentation, but how would I change all header and body font families to a specific type of my choosing?

**Comment by mhartl** [comment]
Thanks for your question. Style customization is covered in [Section 4.2](http://manual.softcover.io/book/customization#sec-commands_and_styles). For specifics, I suggest Googling around for CSS or LaTeX, depending on your specific needs.

**Comment by nickjj** [comment]
Yeah, the style guide doesn't mention how to use a custom font, only how to adjust its size.

Googling for LaTeX is like trying to read the control panel of a Klingon spaceship.

**Comment by mhartl** [comment]
The style guide shows you how to hook into the book's CSS, which lets you control font family as well as size.

Klingon isn't as hard as it looks.

**Comment by nickjj** [comment]
Oh, I wasn't aware you could control the PDF with CSS, I thought that was only for the HTML and epub formats. That simplifies a lot of things.

If that's the case, why did you adjust the global font size with LaTeX instead of CSS?

**Comment by nickjj** [comment]
Google solutions seem to fail as well, for example Google says this is how you change a font with LaTeX:

```
\setmainfont{helvet}
\renewcommand{\familydefault}{\sfdefault}
```

So I put that into my `custom_pdf.sty` and it just throws:

```
! Undefined control sequence.
l.15 \setmainfont
```

**Comment by chkwon** [comment]
@nickjj I believe `\setmainfont{...}` works for `xelatex`. You have to look for `pdflatex` commands.

Try
```
\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}
```

**Comment by nickjj** [comment]
That works, thanks. As for pulling in and baking in non-standard fonts, how would one do that?

Once that mystery is solved I feel like everything else would be easy to Google (like only applying a font to headers, etc.).

**Comment by chkwon** [comment]
Short answer: Don't do it.  :)

Long answer: softcover doesn't support it, mainly because it uses `pdflatex`, not `xelatex`. If you use `xelatex`, you can use any font installed on your computer. It is not impossible to use `xelatex`, but you need to tweak softcover by yourself.

**Comment by nickjj** [comment]
Would that feature be difficult to implement?

Do you think it's a good idea to put that into your manual, such as a list of supported fonts? I think a number of people would really appreciate knowing they can't use custom fonts before investing a lot of time writing a book with softcover.

**Comment by chkwon** [comment]
Changing from pdflatex to xelatex would be a big deal. As a long time LaTeX user, I just use the default font. It is better than any other font, in my opinion, especially for math equations. I think @mhartl just assumed users of softcover are familiar with LaTeX.  

OK. Here is a simple tip which you can play with. After running `sc build:pdf`, open your `yourbook.tex` in the root directory of your softcover book. It will contain many `\include{...}`. Change all to `\include{tmp/....tmp.tex}`. 

Then you can manually compile `yourbook.tex` using any LaTeX compiler you like, such as `xelatex`. So add as many font commands as you like. You may face some issues here and there, but this basically should work. 

NOTE: if you modify the book chapter files and run `sc build:pdf` again, it will overwrite `yourbook.tex`. So make sure that you make a copy of it and work on it. Perhaps you write your own script that does copying `yourbook.tex` and replacing `\include{...}` by `\include{tmp/....tmp.tex}`, etc.

**Comment by nickjj** [comment]
I'm not writing math equations, mainly tech books. How come `helvet` seems to work, is there a definitive list somewhere?

I'm willing to continue using sc if I can find a font combo that suites my needs. Making all of those changes to support latex manually is too much, at that point I'd probably have better luck with another platform or just generating PDFs with Google Docs.

**Comment by mhartl** [comment]
Softcover supports all the fonts supported by the EPUB/MOBI formats (via CSS) and by LaTeX. So any such list would be external to Softcover.

**Comment by robconery** [comment]
Hi all - I'm having the same issue RE fonts. I'm using SourceCode Pro and referencing it this way:

```css
@font-face {
  font-family : 'Source Code Pro', monospace, Courier;
  font-weight : 400;
  font-style: normal;
  src : url(fonts/SourceCodePro-Regular.otf);
}
```

I've then added a `fonts` directory to stylesheets, which doesn't get picked up. I have also moved the fonts all over the project to see if they'll get packed in the OEBPS, but no go.  This is confirmed by calibre's ebook editor, which says the font doesn't exist.

I'm not a fan of Courier (which appears to be the default) but I suppose I can get over it :). Wondering what I might be missing here?

**Comment by mhartl** [comment]
Not sure if it'll work in any case, but you have to scope any custom CSS by book id (`#book`), as described [here](http://manual.softcover.io/book/customization#sec-html_style).

**Comment by robconery** [comment]
Yeah - I'm doing that for the rest of the custom bits; the `@font-face` rule isn't scoped as a DOM identifier (as far as I know... I'm a CSS idiot) – it's just a rule. 

I haven't looked at the code in the gem file, but I'm wondering if putting custom fonts into a special directory somewhere in the same way you do with images (with a symlink in /html) and then preloading that into OEBPS might do the trick.

It's been so long since I've done *any* Ruby, but I can take a look at this and see what I can make of it. For now, using `monospace` does the trick... but SourceCode Pro looks so much nicer...

**Comment by mhartl** [comment]
Definitely interested in supporting something like this, but unfortunately it's not currently a priority. The source is open, though, so have at it if you're feeling up for a challenge!
