### ISSUE TITLE
Adding images vertically offset text by a huge empty margin in PDFs

### ISSUE THREAD

**Issue by nickjj** [softcover/softcover#171]
Example markdown:

```
## Hello world

This is a story about hello world.

\begin{figure}[H]
\image{images/figures/01_hello.jpg}
\caption{Hello world\label{fig:hello}}
\end{figure}

### Something else
```

With the above in place, there will be a massive gap of whitespace between the "hello world" header and the "This is a story about hello world." sentence.

The vertical gap seems to be relative to the size of the image, but it looks really bad because it looks like arbitrary space between the header and text.

The epub format does not have this problem but it's important that it works for PDFs.

How would you fix this, or prevent it from happening?

**Comment by mhartl** [comment]
Unlike EPUB, PDF has the same constraints as a print book, so placing figures can be tricky. In this case, you can remove the `[H]` to fix the issue. Google around on the subject of LaTeX float placement to learn about other options.

**Comment by nickjj** [comment]
Removing the H does not fix the issue, upon removing the H the figure doesn't even show up.

**Comment by ivanistheone** [comment]
As Michael mentioned, this is not the venue to discuss LaTeX difficulties---hundreds of hours have been spent by people all over the world trying to get figures right in latex. Welcome to the club.

I'd recommend `\begin{figure}[htb]` as a good default, though the figure might not end up where you expect it.

For more info, check: https://www.sharelatex.com/learn/Positioning_of_Figures

**Comment by nickjj** [comment]
Would it be unreasonable to make [htb] the default for all images because that did what was expected and it's not mentioned in the guide.

I understand that this might not be the best place but you guys decided to use LaTeX and right now it seems like there's a massive barrier of entry to do extremely common things like change the default body / header fonts, etc.. and no documentation on how to apply what you can find on Google to a softcover book.

**Comment by chkwon** [comment]
@nickjj I usually use `figure` without any position identifiers like `[htb]`. I like that LaTeX determines its location by itself. 

When wide spaces happens, it is because the figure is put along with two many other floating objects such as `figure` and `table`, , new sections, or too little text. Another thing you can try is to put the code for the figure in a different position. Usually earlier than the expected position is desirable. Good luck.

**Comment by nickjj** [comment]
Yeah in my case it was too little text. It tried to position a fairly large image onto its own page without breaking up the preceding text. I experimented with adding a few dummy paragraphs and that pushed it down but [htb] is still producing the best results with the text I had initially.
