### ISSUE TITLE
Elm syntax highlighting

### ISSUE THREAD

**Issue by BrianHicks** [softcover/softcover#173]
It looks like pygments.rb doesn't support Elm syntax highlighting, even though Pygments does. I'd really like to use Softcover for writing about Elm, but this has become a soft blocker. To further complicate things, it looks like pygments.rb is dead or dying.

What would y'all recommend to get unblocked? I'll write my book without syntax highlighting if I need to, but I'd really prefer having it.

(Also @mhartl thanks for the Rails Tutorial. I learned web dev using it when you first published, and I wouldn't be where I am now without your work. Thank you.)

**Comment by mhartl** [comment]
The pygments.rb project seems active enough, with commits within the last month. If it's really true that pygments.rb doesn't support all current Pygments lexers, you might consider reaching out to see if they might be willing to add them. 

At some point, if necessary we could switch Softcover to shell out directly to `pygmentize`, though that would take some dev work on my part, which unfortunately isn't a top priority right now.

Reaching out to the pygments.rb team is probably your best bet, especially if you can figure out how to add the necessary lexer as a pull request!

Thanks for the kind words about the Rails Tutorial. I'm glad you found it useful!

**Comment by BrianHicks** [comment]
Will do, thanks @mhartl. For now I've got it working with the Haskell syntax highlighter… there are a few key differences but it works for 90% of what I need.

**Comment by mhartl** [comment]
:+1:
