### ISSUE TITLE
Trailing spaces in fenced code blocks get chopped out in PDF but not HTML

### ISSUE THREAD

**Issue by nickjj** [softcover/softcover#174]
Example:

```
\begin{codelisting}
\label{code:test}
\codecaption{Test}
~~~
Foo  
~~~
\end{codelisting}
```

I had to replace the back ticks with ~~~ to get around posting this on GitHub.

If you generate the above you'll get a PDF that shows "Foo" but the HTML version will have "Foo  " with 2 spaces after which is the intended result (select Foo in the above code snippet).

How can I get the PDF version to not auto-strip the spaces?

**Comment by mhartl** [comment]
I'm not sure what you're going for here, since trailing spaces won't be visible in any case, but LaTeX strips spaces in this context. Placing something like a comment character at the end, as in

```
Foo  #
```

would produce spaces in the PDF.

**Comment by nickjj** [comment]
Is there any way to do it without placing a character at the end?

I just want the line to end on 2 spaces so I can demonstrate adding single line breaks in markdown by providing a code sample.

**Comment by mhartl** [comment]
> Is there any way to do it without placing a character at the end?

Not that I know of.

> I was under the impression that what I see in the HTML preview is what I would get in the other outputs.

Unfortunately, the different output formats have too many restrictions and idiosyncrasies for this impression to be correct.

>  nothing like the PDF/epub/mobi output

It's not "nothing like" the other output. The outputs are always as similar as the design constraints allow. So far as I know, apart from bizarre edge cases like Markdown's dubious convention of "significant trailing double spaces", the outputs are always functionally the same, but it's impossible in general to know for sure.

I suggest either writing around edge cases (e.g., add a footnote that says "If you're reading the PDF, you'll have to add two trailing spaces by hand…") or picking different examples.

**Comment by nickjj** [comment]
Thanks. I'll work around it with a different example.
