### ISSUE TITLE
Oddly colored back ticks in code fenced listings

### ISSUE THREAD

**Issue by nickjj** [softcover/softcover#175]
Let's say you wanted to show an example of how to output Python code in Markdown as a listing.

Example:

```
\begin{codelisting}
\label{code:fenced_code_blocks}
\codecaption{Creating code blocks with fences}
!!!python, options: "linenos": true
 ~~~python
 def hello():
     return print("Do you know Python?")
 ~~~
!!!
\end{codelisting}
```

I had to use ! and ~ to battle GitHub's editor. In reality those are all back ticks.

In the above example, the third back tick (which is ~ above) would be outlined in red. The "python" text after the third back tick (which is ~ above) is also bolded.

Do you have a better strategy to do what I'm trying to do?  I was looking to output a syntax highlighted Python code example wrapped in a code fence to demonstrate how to do it in Markdown.

That was the only syntax I could come up with that output a PDF in a way that made sense.

**Comment by mhartl** [comment]
The backticks are shown in red to indicate Pygments highlighting errors. This is simply because you've requested Python highlighting, but the triple backtick syntax is not valid Python.

Pygments doesn't have a Markdown parser AFAIK, but you can use plain text, as follows:

![screen shot 2016-12-10 at 18 00 25](https://cloud.githubusercontent.com/assets/6232/21077502/9a9641c0-bf02-11e6-831f-03f4469fa45b.png)

Hope this helps!

**Comment by nickjj** [comment]
But then the python code snippet won't be color highlighted, is that correct?

Is there a way to disable pygment's highlighting errors for a specific code caption? It's important that the Python code itself remains highlighted in the output.

**Comment by mhartl** [comment]
> But then the python code snippet won't be color highlighted, is that correct?

That's right.

> Is there a way to disable pygment's highlighting errors for a specific code caption?

Not that I know of.

> It's important that the Python code itself remains highlighted in the output.

You can't do this using Pygments AFAIK, but Atom appear to handle it as you require, so perhaps you could use an image:

![screen shot 2016-12-11 at 8 55 28 am](https://cloud.githubusercontent.com/assets/6232/21081615/a35dbd4c-bf7f-11e6-8d1a-b75a8bc5bc0b.png)
