### ISSUE TITLE
softcover build:mobi hangs

### ISSUE THREAD

**Issue by mrichman** [softcover/softcover#176]
This is my first time running softcover, so I might be doing something wrong.

`softcover new`
`softcover check` (failed, then I installed all the dependencies and it passed)
`softcover build:pdf` passed
`softcover server` builds and runs fine

but when I do the following, it just hangs forever. I killed it, and got the below stack trace:

```
$ softcover build:mobi 
Building MOBI...
^C/var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/output.rb:36:in ``': Interrupt
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/output.rb:36:in `system'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/builders/epub.rb:289:in `block (2 levels) in html_with_math'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/utils.rb:324:in `silence_stream'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/builders/epub.rb:289:in `block in html_with_math'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/utils.rb:224:in `block in silence'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/utils.rb:324:in `silence_stream'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/utils.rb:223:in `silence'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/builders/epub.rb:289:in `html_with_math'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/builders/epub.rb:256:in `block (2 levels) in write_html'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/builders/epub.rb:238:in `open'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/builders/epub.rb:238:in `block in write_html'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/builders/epub.rb:236:in `each'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/builders/epub.rb:236:in `each_with_index'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/builders/epub.rb:236:in `write_html'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/builders/epub.rb:159:in `build!'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/builders/mobi.rb:8:in `build!'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/commands/build.rb:12:in `for_format'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/lib/softcover/cli.rb:59:in `block (2 levels) in <class:CLI>'
	from /var/lib/gems/2.3.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /var/lib/gems/2.3.0/gems/softcover-1.3.0/bin/softcover:4:in `<top (required)>'
	from /usr/local/bin/softcover:22:in `load'
	from /usr/local/bin/softcover:22:in `<main>'
```

**Comment by mhartl** [comment]
Unfortunately, macOS Sierra broke InkScape, on of Softcover's dependencies. See if [this thread](https://github.com/softcover/softcover/issues/154#issuecomment-266923385) helps resolve it.

**Comment by mrichman** [comment]
I'm on Ubuntu.

**Comment by mhartl** [comment]
Ah, that's good news I suppose. The likeliest cause of hanging is still math output, probably via PhantomJS. If you don't intend to use math in your documents you might be able to route around the issue. If that's the case, try removing the math from the sample document and give it another go.

**Comment by mrichman** [comment]
Well, good and bad. The Ubuntu 16.04 package for Inkscape is 0.91. Not sure if this is incompatible with Softcover on Ubuntu.

Removing the math from the sample chapters fixed the issue, and I don't need math in my book (for now).

Thanks!

**Comment by mhartl** [comment]
:+1:

**Comment by mrichman** [comment]
If one desperately needs LaTeX typeset equations, I suppose they can generate them using pure LaTeX, exporting to .eps or .pdf, and then embed those images back into the softcover markdown, no?

**Comment by mhartl** [comment]
If you ever need to address the issue, you might be able to fix it by uninstalling the system version and [reinstalling Inkscape 0.48.5](https://inkscape.org/en/release/0.48.5/platforms/) from source.

**Comment by mhartl** [comment]
You could do that, but it would look terrible.
