### ISSUE TITLE
How to get rid of page "header" on each page of my book

### ISSUE THREAD

**Issue by alexvbush** [softcover/softcover#182]
hi, searched everywhere and couldn't find an answer. How do I get rid of this page header in my book? My chapter titles are too long and it looks very busy and not well aligned.
![screenshot 2017-04-25 21 29 27](https://cloud.githubusercontent.com/assets/311077/25418144/5515bbb4-29fe-11e7-8684-72f04058517d.png)

**Comment by ivanistheone** [comment]
This is a standard `LaTeX` question, and not specific to `softcover`.

To customize headers/footers in the PDF, you can edit the file `YOURPROJECT/latex_styles/custom.sty` for example you can try, adding this to the bottom of that file:

```
\usepackage{fancyhdr}
\pagestyle{fancy}
\lhead{This is my name in Chapter \thechapter}
\rhead{this is page \thepage}
\cfoot{center of the footer!}
```
from the sounds of it, you probably want something like for a "no frills" approach

```
\usepackage{fancyhdr}
\pagestyle{fancy}
\lhead{}
\rhead{}
\renewcommand{\headrulewidth}{0pt}
\cfoot{\thepage}
```

See https://tex.stackexchange.com/a/87769/10977 and https://www.sharelatex.com/learn/Headers_and_footers for more info.

**Comment by alexvbush** [comment]
it worked! thanks!
