### ISSUE TITLE
Apostrophes are not rendering for PDF in my book

### ISSUE THREAD

**Issue by alexvbush** [softcover/softcover#185]
Hi, I've got a feedback from one of my readers re: spelling mistakes. It turned out that in PDF version of my book all the apostrophes are missing but are rendering fine ePub and mobi. What that could be?

**Comment by mhartl** [comment]
Chances are they're not normal apostrophes, but instead are some sort of ‘curly’ apostrophe. 

If that's the case, I suggest you either replace them with normal ones (they'll still be curly in the output), or else use the `\newunicode` command discussed [here](http://manual.softcover.io/book/customization#sec-pdf_style) to associate them with the regular `'` character. I'm not sure the latter will work, but the former almost certainly will.

**Comment by alexvbush** [comment]
holy crap it is!!! thank you @mhartl !!!

**Comment by alexvbush** [comment]
seems like my editor used apostrophe on her windows keyboard or something

**Comment by alexvbush** [comment]
😄
