### ISSUE TITLE
Using a tilde (`~`) inside backticks freezes the epub builder

### ISSUE THREAD

**Issue by joncalhoun** [softcover/softcover#189]
To replicate:

```
softcover new demo
cd demo
nano chapters/a_chapter.md
```

Add the following inside the chapter: 

```
`~`
```

Then try to build the epub:

```
softcover build:epub
```

It will hang indefinitely it seems, not outputting errors or anything else. It appears that using a `\q` inside of backticks also does this if that helps figure out the root cause. 

I'm also happy to dig myself if you can give a little guidances as to where to start.

**Comment by mhartl** [comment]
I'm unable to reproduce. It works fine on my system. (It renders as `\( \sim \)`, but that's a Markdown artifact. To get a tilde, use `\textasciitilde`.)
