### ISSUE TITLE
No header received back. (MentosError)

### ISSUE THREAD

**Issue by cavalryjim** [softcover/softcover#190]
I'm getting started with Softcover and have successfully completed all the steps up to section 1.1.3 of the Softcover manual (http://manual.softcover.io/book/getting_started#sec-html_softcover_server).  The error occurs when trying to build the HTML version of my book. 

james$ softcover build:html
Building HTML...
/Users/james/.rvm/gems/ruby-2.2.2/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:325:in `handle_header_and_return': No header received back. (MentosError)
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:262:in `block in mentos'
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:233:in `mentos'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:215:in `highlight'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/polytexnic-1.3.1/lib/polytexnic/utils.rb:209:in `highlight'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/polytexnic-1.3.1/lib/polytexnic/utils.rb:170:in `block in highlight_source_code'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `upto'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `each'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/polytexnic-1.3.1/lib/polytexnic/utils.rb:166:in `highlight_source_code'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/polytexnic-1.3.1/lib/polytexnic/postprocessors/html.rb:1291:in `convert_to_html'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/polytexnic-1.3.1/lib/polytexnic/postprocessors/html.rb:58:in `xml_to_html'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/polytexnic-1.3.1/lib/polytexnic/postprocessor.rb:16:in `postprocess'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/polytexnic-1.3.1/lib/polytexnic.rb:89:in `to_html'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/softcover-1.4.5/lib/softcover/builders/html.rb:123:in `converted_html'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/softcover-1.4.5/lib/softcover/builders/html.rb:43:in `build'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/softcover-1.4.5/lib/softcover/builder.rb:18:in `build!'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/softcover-1.4.5/lib/softcover/commands/build.rb:12:in `for_format'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/softcover-1.4.5/lib/softcover/cli.rb:59:in `block (2 levels) in <class:CLI>'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Users/james/.rvm/gems/ruby-2.2.2/gems/softcover-1.4.5/bin/softcover:4:in `<top (required)>'
	from /Users/james/.rvm/gems/ruby-2.2.2/bin/softcover:23:in `load'
	from /Users/james/.rvm/gems/ruby-2.2.2/bin/softcover:23:in `<main>'
	from /Users/james/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/james/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by cavalryjim** [comment]
Additional information:
MacBook Pro, Late 2016
macOS Sierra v 10.12.1

MacBook-Pro:entr4701_book james$ softcover check
Checking Softcover dependencies...
Checking for LaTeX...         Found
Checking for GhostScript...   Found
Checking for ImageMagick...   Found
Checking for Node.js...       Found
Checking for PhantomJS...     Found
Checking for Inkscape...      Found
Checking for Calibre...       Found
Checking for KindleGen...     Found
Checking for Java...          Found
Checking for zip...           Found
Checking for EpubCheck...     Found
All dependencies satisfied.

**Comment by mhartl** [comment]
Can you reproduce the issue with the default book generated by `softcover new`?

**Comment by cavalryjim** [comment]
Yes, this issue was produced with the default book generated by ```softcover new```.  Thus far, I have followed the steps in the manual and have not written any custom content.

**Comment by mhartl** [comment]
[Googling the error message](https://www.google.com/search?q=in+handle_header_and_return%27%3A+No+header+received+back.+(MentosError)+from&oq=in+handle_header_and_return%27%3A+No+header+received+back.+(MentosError)+from&aqs=chrome..69i57.212j0j1&sourceid=chrome&ie=UTF-8) turns up some indications that it might be related to having the wrong Python version on the PATH. I suggest taking a look at some of the threads that turn up in that search to see if they help you resolve the situation.

**Comment by cavalryjim** [comment]
Installed pyenv via homebrew.  After a little configuring, it seems to be working via ```pyenv local 2.7.8```.

**Comment by mhartl** [comment]
👍

**Comment by mhartl** [comment]
Sorry it was so difficult, but glad you got it working!

**Comment by cavalryjim** [comment]
Closing
