### ISSUE TITLE
Can't install softcover CLI

### ISSUE THREAD

**Issue by undavide** [softcover/softcover#192]
Hi,
I'm having a blocking issue while trying to:

```
$ gem install softcover
Building native extensions.  This could take a while...
ERROR:  Error installing softcover:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-0.4.7/ext
/usr/local/opt/ruby/bin/ruby -r ./siteconf20171213-59173-1cn1ua.rb extconf.rb
checking for ruby/st.h... yes
checking for st.h... yes
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-0.4.7/ext
make "DESTDIR=" clean

current directory: /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-0.4.7/ext
make "DESTDIR="
compiling pack.c
pack.c:300:19: error: use of undeclared identifier 'rb_cFixnum'
        rb_define_method(rb_cFixnum, "to_msgpack", MessagePack_Fixnum_to_msgpack, -1);
                         ^
pack.c:301:19: error: use of undeclared identifier 'rb_cBignum'
        rb_define_method(rb_cBignum, "to_msgpack", MessagePack_Bignum_to_msgpack, -1);
                         ^
2 errors generated.
make: *** [pack.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-0.4.7 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-17/2.4.0/msgpack-0.4.7/gem_make.out
```

I'm no master of Ruby (actually I barely know that Ruby exists), so I hacked my way in, thanks Google...
I've downloaded the repository, changed the `softcover.gemspec` like:

```
gem.add_dependency 'msgpack' , '~> 1.2.0'
```

Then run:

```
gem build /Users/davidebarranca/Downloads/softcover-master/softcover.gemspec
```

and eventually tried to build from the local gem:

```
gem install ~/softcover-1.4.6.gem
```

Alas, I'm getting the very same error, referencing the `0.4.7` version of `msgpack`, and softcover still is not installed.
Please note that I only assume `msgpack` has problems, frankly it's a very faint assumption.

FYI, I'm running macOS HighSierra – and had to `brew install ruby` in order to bypass writing permission issues while trying to install softcover.

**Comment by undavide** [comment]
Turns out that `polytexnic` has `msgpack-0.4.7` as a dependency too. I have:

- dowloaded locally the `softcover` repo
- `gem install msgpack` to get the latest version `1.2.0
- downloaded `polytexnic` locally from the repository, pushed the `msgpack` dependency to `1.2.0` in the `.gemspec` and installed it with `gem build /path/to/polytexnic.gemspec` and `gem install /path/to/polytexnic.gem`
- Opened the `softcover.gemspec` file and commented out both `msgpack` and `polytexnic` so that they will not be fetched while installing it (perhaps there's a better way, but as I wrote I'm null at Ruby)
- `gem build /path/to/softcover.gemspec` and `gem install /path/to/softcover.gem`

Apparently, the process is successful but when running `softcover` I get:

```
 🦊  softcover
/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- polytexnic (LoadError)
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/softcover-1.4.6/lib/softcover.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/softcover-1.4.6/bin/softcover:2:in `<top (required)>'
	from /usr/local/bin/softcover:23:in `load'
	from /usr/local/bin/softcover:23:in `<main>'
```

Further inspection shows that the folder `/usr/local/lib/ruby/gems/2.4.0/gems/polytexnic-1.3.1` exists, but it is empty. ARRGH...

Any suggestion is greatly appreciated. Thank you!

**Comment by mhartl** [comment]
As [mentioned](http://manual.softcover.io/book/getting_started#sec-installing_softcover) in the Softcover manual, Ruby 2.4 isn't currently supported, so that could be the problem. @nickmerwin is already on the case, though, so 2.4 support should be out soon.

**Comment by mhartl** [comment]
Ruby 2.4+ support has been available for a while, so I’m closing this issue.
