### ISSUE TITLE
Soft breaks?

### ISSUE THREAD

**Issue by marcocevoli** [softcover/softcover#195]
Hi, 
I'm not sure this is the right place to ask, but since I can't find other communities for Softcover.io, I'll try here.

How can you insert soft line breaks in the text? Usually, in markdown you put 2 spaces before the Line Feed, but this is not working. I get a hard return, that is, the text goes on an new line, but with the same spacing as if I separate a paragraph from each other. Instead, I'd like to put an address in the preface/colophon, so I'd like to have those lines close together. Any workaround?

**Comment by mhartl** [comment]
I believe you can do this by creating a [raw LaTeX book](http://manual.softcover.io/book/polytex_tutorial) and using a double backslash `\\`:

```
This is a line \\
And another line \\
And a third line
```
