### ISSUE TITLE
Right align?

### ISSUE THREAD

**Issue by marcocevoli** [softcover/softcover#196]
Hi, I'd like to know how you can right align a paragraph. 

Somewhere I read you can use a div with attribute text-align:right, tried that, but it's not working. The text between div tags disappears. Maybe because I also need to put a small caps Latex tag.

This is the code:
```
Long chunk of text...
<div style="text-align:right">
\textsc{john doe}

CEO of Acme, Inc.
</div>
```
Any ideas?

**Comment by mhartl** [comment]
Unfortunately, I don't know of any way to right-align text.
