### ISSUE TITLE
Link in figure caption?

### ISSUE THREAD

**Issue by doodl3** [softcover/softcover#199]
Hi guys, thanks for this awesome publishing software.

I'd like to ask how do @mhartl insert link in figure caption like the one here? 

https://www.learnenough.com/command-line-tutorial#fig-regex_101

The caption figure 20: has that online regex builder link. I've tried the follow but did not work. 

```markdown
![this my caption with a [link](url) \label{fig:my-image.png}](my-image.png)
```

Thanks for any help!

**Comment by mhartl** [comment]
Thanks for your question. I'm not sure if you can do it in Markdown, but I used raw LaTeX, as follows:

```latex
\begin{figure}
\begin{center}
\image{images/figures/regex_101.png}
\end{center}
\caption{An \href{https://regex101.com/}{online regex builder}.\label{fig:regex_101}}
\end{figure}
```

See [Section 3.3](http://manual.softcover.io/book/softcover_markdown#sec-embedded_latex) in the Softcover manual for more information on using embedded LaTeX with Softcover.

Hope this helps!
