### ISSUE TITLE
Font Times not available

### ISSUE THREAD

**Issue by git001** [softcover/softcover#200]
There is #170 where the font question is mentioned.  
My issue is that I always get the error that `Times` font isn't available. This is also mentioned in this answer https://tex.stackexchange.com/a/81766

```
root@docinst:~/example_book# fc-list |egrep -i times
root@docinst:~/example_book# 
```
It's on this linux distribution

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

I have tried to install msfonts but this does not change anything

The font is specified in this file.  
Which process/program generates this file?

https://github.com/softcover/softcover/blob/master/lib/softcover/book_template/latex_styles/softcover.sty#L210-L217

Now when I try to change the main font as described in https://github.com/softcover/softcover/issues/170#issuecomment-254865934 in `custom_pdf.sty`

```
cat latex_styles/custom_pdf.sty
% You should use this file to define commands that *only* pertain to the PDF.
% Otherwise, use `custom.sty`.
% For example, you can define the proper hypenation of any words that LaTeX
% can't hyphenate natively.
% \hyphenation{Ja-va-Script}
% You can also include and use packages.
% \usepackage{newunicodechar}
% \newunicodechar{★}{\ensuremath{\star}}
% \newunicodechar{ž}{\v{z}}

\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}
```

I still get the following error

```
Transcript written on mfput.log.
grep: Times.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input Times' failed to make Times.tfm.
kpathsea: Appending font creation commands to missfont.log.


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
!
! The font "Times" cannot be found.
!
! See the fontspec documentation for further information.
!
! For immediate help type H <return>.
!...............................................

l.216             {Times}

?
! Emergency stop.
!...............................................

l.216             {Times}
```
Full output from build:pdf https://gist.github.com/git001/1d3299d835c9f364f0e76b8580b9b0c1

My install commands.
```
apt -y install ruby2.5-dev ri ruby-dev bundler zlib1g-dev libxml2-dev libcurl4-openssl-dev libssl-dev nodejs  phantomjs imagemagick dia libwmf-bin pstoedit sketch inkscape calibre default-jre texlive-full

# copy kindlegen tgz to server
mkdir /usr/local/kindlegen_linux_2.6_i386_v2_9
tar xfvz kindlegen_linux_2.6_i386_v2_9.tar.gz -C /usr/local/kindlegen_linux_2.6_i386_v2_9
ln -s /usr/local/kindlegen_linux_2.6_i386_v2_9/kindlegen /usr/local/bin/

curl -vLO https://github.com/IDPF/epubcheck/releases/download/v4.0.2/epubcheck-4.0.2.zip
unzip -d /usr/local/bin/ epubcheck-4.0.2.zip

gem install softcover --pre --no-ri --no-rdoc

softcover version
Softcover 1.5.6

softcover check
Checking Softcover dependencies...
Checking for LaTeX...         Found
Checking for GhostScript...   Found
Checking for ImageMagick...   Found
Checking for Node.js...       Found
Checking for PhantomJS...     Found
Checking for Inkscape...      Found
Checking for Calibre...       Found
Checking for KindleGen...     Found
Checking for Java...          Found
Checking for zip...           Found
Checking for EpubCheck...     Found
Checking for Python 2...      Found
All dependencies satisfied.
```

**Comment by mhartl** [comment]
Sorry for the trouble. You can try overriding `\setmainfont` in `latex_styles/custom_pdf.sty` and see if that works. You can also try downloading the [source](https://github.com/softcover/softcover) and seeing if changing `softcover.sty` directly fixes the issue. If so, you could add a Linux-specific file and then use that if the system making the call to `softcover` is Linux. I would be happy to accept a pull request to this effect.

I understand that digging into the source code can be a pain, but unfortunately I don’t generally have the resources to track down and fix issues like this. Sorry I can’t be more helpful.

**Comment by git001** [comment]
> Sorry for the trouble. You can try overriding `\setmainfont` in `latex_styles/custom_pdf.sty` and see if that works

I have tried this way but it's to late as the https://github.com/softcover/softcover/blob/master/lib/softcover/book_template/latex_styles/softcover.sty calls `latex_styles/custom_pdf.sty` where the `\setmainfont` is defined.

The comment in https://github.com/softcover/softcover/blob/master/lib/softcover/book_template/latex_styles/softcover.sty#L1 suggest that the file is generated maybe the generator can be configured to not set fonts on linux?

**Comment by nathansebhastian** [comment]
I'm having the same problem here... Weird since tex-live-fonts-recommended has the font. Were you able to solve this? @git001

**Comment by swhgoon** [comment]
`
% Add smallcaps
\usepackage{fontspec}
\setmainfont[ItalicFont     = Times New Roman Italic,
             BoldFont       = Times New Roman Bold,
             BoldItalicFont = Times New Roman Bold Italic,
             SmallCapsFont=Bodoni 72 Smallcaps]
            {Times New Roman}
\setmonofont{Courier New}
`
