### ISSUE TITLE
Curb failed to build

### ISSUE THREAD

**Issue by jbwyatt4** [softcover/softcover#201]
Hello,

Softcover's uses an out of date version of curb (0.8.8) that does not build successfully on Manjaro (Arch) when you try to install it by gem. Please update it to the latest version which I have verified does build.

**Comment by inetbiz** [comment]
https://github.com/softcover/softcover/blob/master/softcover.gemspec#L28 Is this resolved?

**Comment by mhartl** [comment]
Yes, the latest version uses curb 0.9.7.
