### ISSUE TITLE
FEATURE: Add JSON+LD to books

### ISSUE THREAD

**Issue by inetbiz** [softcover/softcover#204]
http://manual.softcover.io/ for example does output **json+ld** for semantic search. https://search.google.com/structured-data/testing-tool?hl=en-GB#url=http%3A%2F%2Fmanual.softcover.io%2F

You have several schema types to graph. The book, book offers, author, reviews, aggregate reviews, faq schema. The main entity of the page should be book schema.

**Comment by mhartl** [comment]
Softcover is feature-complete for our purposes, so any additional features will have to be driven by changes in our requirements or by community contributions. 

I’d be happy to accept (fully tested) pull requests of new functionality.
