### ISSUE TITLE
Paragraph line spacing for book but not Table of Contents

### ISSUE THREAD

**Issue by sw-yx** [softcover/softcover#216]
Hi @mhartl, thank you so much for softcover!

Latex's default is to have no spacing between paragraphs, which makes it a little hard to read, so I figured out that I could [add paragraph linespacing](https://www.overleaf.com/learn/latex/paragraph_formatting#Line_spacing) to do it: 

```
\setlength{\parskip}{1em}
```

This looks good:

![image](https://user-images.githubusercontent.com/6764957/82422531-280e3800-9ab5-11ea-9610-2425caceb194.png)

The problem is that it also applies to Table of Contents, which now look way too spread out (i have like 10 pages of ToC now): 

![image](https://user-images.githubusercontent.com/6764957/82422604-3c523500-9ab5-11ea-83fa-e36e33776772.png)

Is there any way to specifically make `custom.sty` formatting only for mainmatter content please? I have not been able to figure this out, softcover complains if i try to place latex formatting anywhere inside the book. thank you!

**Comment by mhartl** [comment]
Thanks for your question. `custom.sty` goes right into the PDF build, so there’s nothing Softcover-specific about it; it’s handled purely by LaTeX. Thus, AFAICT you’re likelier to find an answer to your question about “formatting only for mainmatter content” in a LaTeX-specific FAQ or forum.

**Comment by sw-yx** [comment]
thanks. i wasnt able to figure it out.. a bit of googling found this https://tex.stackexchange.com/questions/148125/change-format-of-the-contents-page but it wasnt clear whether this belonged in `custom.sty` at all since i needed my mainmatter styling to only be inserted after `/mainmatter`. giving up for now. good luck to whoever finds this
