### ISSUE TITLE
Emoji support?

### ISSUE THREAD

**Issue by sw-yx** [softcover/softcover#217]
Hi, simple question - how do I enable emoji support? 😂  I'm pretty sure the font i'm using supports emojis, but it just doesnt display when I generate a PDF. any tips?

I'm sure this is some sort of Latex question but I'm not sure where to start. Can anyone point me the right way?

**Comment by ivanistheone** [comment]
Hi, simple question - how do I enable emoji support? 😂 I'm pretty sure the
> font i'm using supports emojis, but it just doesnt display when I generate
> a PDF. any tips?
>
I'm sure this is some sort of Latex question but I'm not sure where to
> start. Can anyone point me the right way?
>
>
> This seems like a good starting point
https://tex.stackexchange.com/a/59126/10977

For debugging try to edit and build the .tex manually with xelatex (not
pdflatex)

then add customizatations to one of the files in the latex_styles dir, e.g.
https://github.com/softcover/softcover_book/blob/master/latex_styles/custom_pdf.sty

**Comment by sw-yx** [comment]
thanks @ivanistheone ! i got it half working:
![image](https://user-images.githubusercontent.com/6764957/82480721-cbd40400-9b06-11ea-8266-32f32770a13d.png)


i use this in `custom.sty`:

```
% set font
\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}

% emoji support https://tex.stackexchange.com/questions/3695/smileys-in-latex/59126#59126
\usepackage{fontspec}
\newfontfamily\DejaSans{DejaVu Sans}
```

and i do this in the markdown:

```
If I don’t help you get past this stage, there **is** no coding career \DejaSans 😱\familydefault
```

i think i'm almost there, need to figure out how to reset the font. thanks.. i'll try to figure this out.

**Comment by sw-yx** [comment]
ok i cant figure it out. its not THAT impt to me so going to close it. good luck whoever finds this in future.
