### ISSUE TITLE
Why are new chapters only begun on odd numbered pages?

### ISSUE THREAD

**Issue by sw-yx** [softcover/softcover#218]
Hi! I noticed something strange in the generated PDF - softcover inserts blank pages just enough that new chapters only begin on odd pages:

![softcover](https://user-images.githubusercontent.com/6764957/82429853-1df13700-9abf-11ea-9f90-86966634febe.gif)

is this intentional behavior? is this customizable behavior? thank you.

**Comment by ivanistheone** [comment]
> Hi! I noticed something strange in the generated PDF - softcover inserts
> blank pages just enough that new chapters only begin on odd pages:
>
> is this intentional behavior?
>

This is standard LaTeX/book behaviour — which makes sense for print books.





is this customizable behavior? thank you.
>

Yes; you'll have to change:

     \documentclass[14pt]{extbook}    -->    \documentclass[14pt,oneside]{
extbook}

in your books's preamble.tex file
https://github.com/softcover/softcover_book/blob/master/config/preamble.tex#L1

**Comment by sw-yx** [comment]
thank you!!
