### ISSUE TITLE
Table of Contents - sections with double digits have bad spacing

### ISSUE THREAD

**Issue by sw-yx** [softcover/softcover#219]
hi! I have some sections that go up to 10 or 12, this is how it looks:

![image](https://user-images.githubusercontent.com/6764957/82707576-ecd75900-9cae-11ea-8c0c-d0b54886e3a6.png)

so it seems like there is some absolute positioning going on?

I know the answer is probably "google some more latex", and i've tried that without a lot of success, especially since the ToC is auto inserted by softcover so I don't have a lot of visibility as to what i can change and where I should change it. So I'm once again asking for help (sorry i know i have been rather needy the last few days.. thats because I'm really using the heck out of this awesome tool!). Any pointers to how to add spacing to this thing? I'm fine with it even if it means i just add absolute spacing  to the single digit sections

**Comment by mhartl** [comment]
Heh, your guess is basically right—this is a LaTeX issue, not a Softcover issue. Unfortunately, we don’t have the resources to answer general questions about LaTeX.

**Comment by mhartl** [comment]
The ToC isn’t inserted by Softcover, by the way: you are fully in control of that via `Book.txt` or `<yourbookname>.tex`, depending on how bare-metal your setup is (see [Chapter 6](https://manual.softcover.io/book/polytex_tutorial) in the manual for more).

**Comment by sw-yx** [comment]
thanks Michael, I understand. i guess i was happy with the autogenerated tableofcontents inserted via Book.txt except for this one little detail 😂 I reckon what you're saying is i should remove the autogenerated one, and just write my own ToC.

**Comment by sw-yx** [comment]
leaving a trail for future adventurers - managed to figure this one out by removing the default `tableofcontents` from `Book.txt`, and dropping in a `toc.md` that contained 

```
\makeatletter
\renewcommand{\l@section}{\@dottedtocline{1}{1.5em}{2.6em}}
\renewcommand{\l@subsection}{\@dottedtocline{2}{4.0em}{3.6em}}
\renewcommand{\l@subsubsection}{\@dottedtocline{3}{7.4em}{4.5em}}
\makeatother
\tableofcontents
\newpage
```

resources:

        - https://www.latex-tutorial.com/tutorials/table-of-contents/
        - double digit spacing https://stackoverflow.com/questions/33093493/adding-space-after-section-numbers-in-toc
