### ISSUE TITLE
multiline blockquotes work in pdf, but not in epub/mobi

### ISSUE THREAD

**Issue by sw-yx** [softcover/softcover#220]
hi folks! no expectation that this will be resolved right away but just reporting something I discovered.

in markdown you can do multiline blockquotes like this:

```
> Croissant wafer danish wafer brownie donut soufflé snaps icing. sugar
sugar plum caramels.
> 
> Jelly-o licorice oat cake icing jelly-o topping donut cake apple pie lemon drops
>
> Marzipan chocolate bar. gummies soufflé topping.
```

which looks like:

> Croissant wafer danish wafer brownie donut soufflé snaps icing. sugar
sugar plum caramels.
> 
> Jelly-o licorice oat cake icing jelly-o topping donut cake apple pie lemon drops
>
> Marzipan chocolate bar. gummies soufflé topping.

I do this in my book, which looks fine on PDF:

![image](https://user-images.githubusercontent.com/6764957/83347030-6ed11d00-a354-11ea-9e1a-fb4ce6b38f74.png)

However it doesn't show up at all in epub/mobi:

![image](https://user-images.githubusercontent.com/6764957/83347040-81e3ed00-a354-11ea-9f55-f8e39c54daa9.png)

I converted the EPUB to HTML and inspected it and it looks like the `<blockquote class="quotation">` doesn't even show up in epub/mobi! it just looks like a regular series of `<p>` tags! this is unusual because in the PDF version it is definitely targetable [and stylable](https://tex.stackexchange.com/questions/33219/whats-the-difference-between-the-environments-quote-and-quotation)!

a normal blockquote would look like this in HTML:

![image](https://user-images.githubusercontent.com/6764957/83347109-13ebf580-a355-11ea-9d63-3cc1b4ed258f.png)

and this looks fine in epub. however when i write multiline blockquotes, softcover generates just the raw `<p>` tags without `<blockquote>`:

![image](https://user-images.githubusercontent.com/6764957/83347122-3aaa2c00-a355-11ea-8de4-b338732f06db.png)

is this a bug with softcover or some underlying dependency? I looked around and i'm pretty sure this isn't a latex issue.

**Comment by mhartl** [comment]
Thanks for the report. Unfortunately, I am unable to reproduce the issue you describe. On my system, the blockquote appears as advertised in both EPUB and MOBI formats:

![Screen Shot 2020-05-31 at 11 55 04 AM](https://user-images.githubusercontent.com/6232/83360457-5520dd00-a336-11ea-8c26-1ef33d148ccc.png)
![Screen Shot 2020-05-31 at 11 59 52 AM](https://user-images.githubusercontent.com/6232/83360458-59e59100-a336-11ea-8366-ba465d325990.png)

You can see a repo of the code I used here:

<https://github.com/mhartl/test_book>

**Comment by sw-yx** [comment]
thanks Michael! this is a great hint, it must be a package I am using then, sorry I thought it was a softcover thing.
