### ISSUE TITLE
Ignore epub OEBPS xhtml files

### ISSUE THREAD

**Issue by jcandan** [softcover/softcover#226]
### Problem

Generated epub files are not ignored by default.

### Expected behavior

Generated epub files should be ignored by default.

### Proposed resolution

Default git ignore rules target `*.html` files in the epub OEBPS folder allowing the generated `*.xhtml` files to be committed.

Add a rule to ignore `epub/OEBPS/*.xhtml`.

**Comment by mhartl** [comment]
Thanks for the heads-up. I was sure I’d updated this, and indeed I had—for every case except books (as opposed to articles) using Markdown. (Markdown articles and LaTeX books/articles already had the proper `.gitignore` rule to ignore `*.xhtml` files.) I’ve updated that one remaining case and released a new version of the `softcover` gem:

```
$ gem install softcover -v 1.7.3
```

Thanks again for your help!
