### ISSUE TITLE
Separate src and dist files

### ISSUE THREAD

**Issue by jcandan** [softcover/softcover#227]
### Problem/Motivation

A project would want to ignore generated files or build artifacts, especially in the context of a CI pipeline. However, upon build of a book template project with no changes, the following git changes show.

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   latex_styles/language_customization.sty

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        html/stylesheets/pygments.css
        latex_styles/polytexnic_commands.sty
        latex_styles/pygments.sty
```

It makes me wonder why latex_styles would be affected during build, are these project-specific configurations or build artifacts? Should the entire `latex_styles` directory be ignored?

Same question for css. Are some files generated and others not?

```patch
 $ git diff
diff --git a/latex_styles/language_customization.sty b/latex_styles/language_customization.sty
index 98429c6..96e78a2 100644
--- a/latex_styles/language_customization.sty
+++ b/latex_styles/language_customization.sty
@@ -1,5 +1,3 @@
-% This file is automatically overwritten; do not edit.
-
 % Aside box label
 \renewcommand{\boxlabel}{Box}
 
@@ -8,4 +6,4 @@
 \DeclareCaptionFormat{listing}{\hspace{-0.2em}\colorbox[gray]{.85}{\hspace{0.1em}\parbox{0.997\textwidth}{#1#2#3}}\vspace{-1.3\baselineskip}}
 \captionsetup[listing]{format=listing,labelfont=bf,skip=16pt,font={rm,normalsize}}
 \DeclareCaptionType{listing}
-\newcommand{\codecaption}[1]{\captionof{listing}{#1}}
\ No newline at end of file
+\newcommand{\codecaption}[1]{\captionof{listing}{#1}}
```

The message that is removed upon build--"This file is automatically overwritten..."--has me thinking that the latex_styles should be ignored, but I could also see the argument being made that a project owner may want to customize these configurations, and they should therefore be unignored. If some are generated, well, then they can't be customized.

If this is the case, can I suggest adopting a `dist/` and `src/` folder structure. Essentially, everything in `dist/` are the distribution build artifacts, while `src/` contains any project specific, modifiable files.

### Steps to reproduce

```
softcover new ExampleBook
cd ExampleBook
git init
git add .
git commit -m "initial commit"
softcover server
git status
git diff
git add .
git commit -m "post server changes"
softcover build
git status
git diff
git add .
git commit -m "post build changes"
```

**Comment by mhartl** [comment]
The files in question are generated on building a new book but not as part of `softcover new`. You can try ignoring them, but this might result in unpredictable behavior, and it does no harm to include them in the repository.
