### ISSUE TITLE
Insert blank line(s) in a PDF

### ISSUE THREAD

**Issue by ayushn21** [softcover/softcover#232]
This is a pretty stupid question in my mind, but it's doing my head in. I'd really appreciate some guidance.

How can I insert one or more blank lines between paragraphs in the PDF export?

If I do something like:

```
Lorem ipsum dolor sit amet

consectetur adipiscing elit
```

In the PDF export, those appear on consecutive lines with the second line indented. This is fine, but how I can manually insert a blank line between these?

I tried `<br />`, `\\`, `\newline` and half a dozen other things but nothing worked. Is this possible to do?

Thanks!

**Comment by mhartl** [comment]
Thanks for your question. This is actually a LaTeX question since Softcover’s PDF output is processed directly with LaTeX. You can try something like this to see if it works:

```latex
\noindent Lorem ipsum dolor sit amet

\medskip

\noindent consectetur adipiscing elit
```

**Comment by ayushn21** [comment]
Thanks for replying so quickly! That indeed did the trick; I went with `\bigskip` but thanks so much for pointing me in the right direction.
